"use client";

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Calendar, Clock, Download, BookOpen, Zap, MessageSquare, Video, Info, LayoutGrid } from 'lucide-react';

const contentTypes = {
  educational: { label: 'Educational', icon: <BookOpen size={14} />, color: 'text-blue-400', bg: 'bg-blue-400/10 border-blue-400/20' },
  promotional: { label: 'Promotional', icon: <Zap size={14} />, color: 'text-gold', bg: 'bg-gold/10 border-gold/20' },
  engagement: { label: 'Engagement', icon: <MessageSquare size={14} />, color: 'text-green-400', bg: 'bg-green-400/10 border-green-400/20' },
  content: { label: 'Brand/Lifestyle', icon: <Video size={14} />, color: 'text-purple-400', bg: 'bg-purple-400/10 border-purple-400/20' },
  rest: { label: 'Rest Day', icon: <Clock size={14} />, color: 'text-grey', bg: 'bg-white/5 border-white/10' }
};

const industryContent = {
  ecommerce: { 
    educational: ['Product Care Tips', 'Shopping Guide', 'How to spot quality', 'Style combinations'], 
    promotional: ['Flash Sale Alert', 'New Arrivals Showcase', 'Limited Stock Warning', 'Bundle Offer'], 
    engagement: ['Poll: Favorite Color?', 'Tag a friend who needs this', 'Customer Question Q&A', 'Giveaway Announcement'], 
    content: ['Warehouse/Office Tour', 'Unboxing Video', 'Order packing process', 'Customer unboxing'] 
  },
  service: { 
    educational: ['Industry Expert Tips', 'How our service works', 'Common mistakes to avoid', 'Case study breakdown'], 
    promotional: ['New Service Launch', 'Special Seasonal Offer', 'Consultation Discount', 'Success Story Feature'], 
    engagement: ['Ask us anything', 'Poll: Business pain point', 'Behind the desk tour', 'Client feedback spotlight'], 
    content: ['Meet the team', 'A day in the office', 'Tool/Software we use', 'Strategy session snippet'] 
  },
  education: { 
    educational: ['Quick Learning Tip', 'Course Preview snippet', 'Study Hack of the day', 'Vocabulary/Term breakdown'], 
    promotional: ['Enrollment Closing Soon', 'Early Bird Discount', 'New Course Announcement', 'Scholarship Opportunity'], 
    engagement: ['Knowledge Quiz', 'Poll: Goal for the week', 'Success Challenge', 'Student Q&A'], 
    content: ['Student Spotlight', 'Teacher intro', 'Classroom/Platform tour', 'Graduation highlight'] 
  },
  health: { 
    educational: ['Nutrition/Health Tip', 'Correct posture/form', 'Wellness routine hack', 'Common health myth'], 
    promotional: ['Package Special Price', 'New Workout Plan', 'Consultation Booking', 'Supplement/Product sale'], 
    engagement: ['Fitness Goal Poll', '30-Day Challenge update', 'Healthy recipe vote', 'Community Q&A'], 
    content: ['Client Transformation', 'Morning routine', 'Healthy meal prep', 'Workout snippet'] 
  },
  food: { 
    educational: ['Quick Recipe share', 'Cooking technique', 'Food pairing tip', 'Ingredient spotlight'], 
    promotional: ['Daily Special Menu', 'Combo Deal Alert', 'Happy Hour Promo', 'New Menu Item'], 
    engagement: ['Vote: Jollof vs Fried', 'Comment your order', 'Chef Q&A', 'Rate this plate'], 
    content: ['Kitchen/Chef Tour', 'Plating process', 'Sourcing ingredients', 'Restaurant vibe video'] 
  }
};

const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

interface DayPlan {
  day: string;
  type: keyof typeof contentTypes;
  content: string;
}

export default function ContentCalendarGenerator() {
  const [industry, setIndustry] = useState('ecommerce');
  const [frequency, setFrequency] = useState(5);
  const [calendar, setCalendar] = useState<DayPlan[]>([]);

  const generateCalendar = (e: React.FormEvent) => {
    e.preventDefault();
    const activeTypes: ('educational' | 'promotional' | 'engagement' | 'content')[] = ['educational', 'promotional', 'engagement', 'content'];
    const newCalendar: DayPlan[] = [];
    
    let typeIndex = 0;
    for (let i = 0; i < 7; i++) {
      if (i < frequency) {
        const type = activeTypes[typeIndex % activeTypes.length];
        const contentOptions = industryContent[industry as keyof typeof industryContent][type];
        const content = contentOptions[Math.floor(Math.random() * contentOptions.length)];
        
        newCalendar.push({
          day: days[i],
          type: type,
          content: content
        });
        typeIndex++;
      } else {
        newCalendar.push({ 
          day: days[i], 
          type: 'rest', 
          content: 'Focus on Stories only or community engagement' 
        });
      }
    }
    setCalendar(newCalendar);
  };

  const downloadCalendar = () => {
    if (calendar.length === 0) return;
    let text = '📅 WEEKLY CONTENT CALENDAR\n\n';
    calendar.forEach((d) => {
      text += `${d.day}: [${contentTypes[d.type].label}] - ${d.content}\n`;
    });
    text += '\nGenerated by Hephzibah Media Strategy Tools';
    
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `content-calendar-${industry}.txt`;
    a.click();
  };

  return (
    <div className="max-w-7xl mx-auto space-y-12">
      {/* Input Section */}
      <div className="glass p-8 md:p-12 space-y-8">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="flex items-center gap-4">
            <div className="w-10 h-10 bg-electric-blue/10 flex items-center justify-center text-electric-blue">
              <Calendar size={20} />
            </div>
            <div>
              <h3 className="text-xl font-bold text-white tracking-tight">Calendar Parameters</h3>
              <p className="text-grey text-xs">Tailor your strategy to your industry and capacity.</p>
            </div>
          </div>
          
          <form onSubmit={generateCalendar} className="flex flex-wrap gap-4">
            <div className="flex flex-col gap-1.5">
              <label className="text-[10px] uppercase tracking-widest text-grey font-bold">Industry</label>
              <select 
                value={industry}
                onChange={(e) => setIndustry(e.target.value)}
                className="bg-midnight-lt border border-white/10 px-4 py-2 text-white text-sm focus:border-electric-blue/50 outline-none appearance-none min-w-[160px]"
              >
                <option value="ecommerce">E-commerce</option>
                <option value="service">Services</option>
                <option value="education">Education</option>
                <option value="health">Health & Wellness</option>
                <option value="food">Food & Beverage</option>
              </select>
            </div>
            
            <div className="flex flex-col gap-1.5">
              <label className="text-[10px] uppercase tracking-widest text-grey font-bold">Posts / Week</label>
              <select 
                value={frequency}
                onChange={(e) => setFrequency(Number(e.target.value))}
                className="bg-midnight-lt border border-white/10 px-4 py-2 text-white text-sm focus:border-electric-blue/50 outline-none appearance-none min-w-[120px]"
              >
                <option value={3}>3 Posts</option>
                <option value={5}>5 Posts</option>
                <option value={7}>7 Posts (Daily)</option>
              </select>
            </div>

            <button type="submit" className="bg-white text-midnight px-8 py-2 self-end font-bold uppercase tracking-widest hover:bg-electric-blue hover:text-white transition-all text-xs">
              Generate Plan
            </button>
          </form>
        </div>
      </div>

      <AnimatePresence mode="wait">
        {calendar.length > 0 ? (
          <motion.div 
            key="calendar-grid"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-8"
          >
            <div className="grid grid-cols-1 md:grid-cols-4 lg:grid-cols-7 gap-px bg-white/5 border border-white/5">
              {calendar.map((d) => (
                <div key={d.day} className="bg-midnight-mid p-6 space-y-4 min-h-[220px] relative overflow-hidden group">
                  <div className="flex justify-between items-start">
                    <span className="text-[10px] uppercase tracking-widest text-grey font-bold">{d.day}</span>
                    <div className={contentTypes[d.type].color}>{contentTypes[d.type].icon}</div>
                  </div>
                  
                  <div className="space-y-3">
                    <span className={`text-[9px] px-2 py-0.5 rounded font-bold uppercase tracking-widest inline-block ${contentTypes[d.type].bg} ${contentTypes[d.type].color}`}>
                      {contentTypes[d.type].label}
                    </span>
                    <p className="text-white text-sm leading-relaxed font-medium group-hover:text-electric-blue transition-colors">
                      {d.content}
                    </p>
                  </div>

                  <div className="absolute -bottom-4 -right-4 w-12 h-12 bg-white/5 rounded-full blur-xl group-hover:bg-electric-blue/10 transition-colors" />
                </div>
              ))}
            </div>

            <div className="flex flex-col md:flex-row items-center justify-between gap-6 p-8 bg-midnight-mid border border-white/5">
              <div className="flex items-start gap-4">
                <div className="mt-1 text-electric-blue"><Info size={20} /></div>
                <div className="space-y-1">
                  <p className="text-white font-bold text-sm">Strategic Mix Enabled</p>
                  <p className="text-grey text-xs leading-relaxed max-w-lg">
                    This plan follows the 4:1:1 rule. 4 pieces of engagement/educational content for every 1 promotional piece and 1 behind-the-scenes update.
                  </p>
                </div>
              </div>
              <button 
                onClick={downloadCalendar}
                className="flex items-center gap-3 bg-white/5 border border-white/10 px-8 py-4 text-white font-bold uppercase tracking-widest hover:bg-white hover:text-midnight transition-all text-xs"
              >
                <Download size={16} /> Download as TXT
              </button>
            </div>
          </motion.div>
        ) : (
          <div className="h-[400px] bg-midnight-mid border border-white/5 flex flex-col items-center justify-center text-center p-12 space-y-6">
            <div className="w-20 h-20 bg-white/5 flex items-center justify-center rounded-full text-grey/20">
              <LayoutGrid size={40} />
            </div>
            <div className="space-y-2">
              <h4 className="text-white font-bold">No Calendar Generated</h4>
              <p className="text-grey text-sm max-w-xs mx-auto">Select your industry and posting frequency to build your weekly content strategy.</p>
            </div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
